### ISSUE TITLE
URLs should become hyperlinks

### ISSUE THREAD

**Issue by shingtaklam1324** [leanprover-community/doc-gen#105]
For example, see

https://leanprover-community.github.io/mathlib_docs/linear_algebra/quadratic_form.html

where under "References", there are 2 URLs, which are not hyperlinks.

![image](https://user-images.githubusercontent.com/15098580/103477753-a927fe80-4dfc-11eb-92da-aa35498f1be5.png)

---

Also, I'm not sure if this is something that `doc-gen` should do, or whether the mathlib style guide should say that urls in doc strings should be markdown links.

**Comment by bryangingechen** [comment]
It looks like we might be able to get `markdown2` (used in `doc-gen`) to convert links automatically by following the steps [described here](https://github.com/trentm/python-markdown2/wiki/link-patterns#converting-links-into-links-automatically).

**Comment by robertylewis** [comment]
@bryangingechen do you know if this is any easier with mistletoe? I don't think it's a big deal or worth much effort. (We can change those urls to proper markdown links.)

**Comment by bryangingechen** [comment]
I think it would be comparable; we'd have to create a regex to pick up raw URLs (maybe we could use the ones in the link above?) and then tell mistletoe to render them as links. (I'll test this out and report back when I can.)
