### ISSUE TITLE
Small left sidebar tweaks

### ISSUE THREAD

**Issue by arthurpaulino** [leanprover-community/doc-gen#139]
* When clicking on the "General documentation" links, the scrollbar disappears and then resets to the top. This is more noticeable when clicking on the "tactics" link. Is it easy/possible to make the left sidebar fixed?
* ~~The "Additional documentation" links open the links on the same tab. Do you think we could make the links be open on a new tab?~~

**Comment by eric-wieser** [comment]
What exactly do you mean on your first bullet point? Are you just complaining that the page loads slowly (because it is large!) and that the sidebar loads last?

**Comment by arthurpaulino** [comment]
@eric-wieser I'm proposing that the sidebar can be loaded once and once only. It requires some front-end trickery but I'm not skilled enough to know how it's done.

Somehow the content of the central page can be reloaded/replaced with javascript while keeping the sidebar still.

**Comment by arthurpaulino** [comment]
Eh, actually this is too minor.
