### ISSUE TITLE
bottom of middle column gets cut off in mobile Safari

### ISSUE THREAD

**Issue by bryangingechen** [leanprover-community/doc-gen#14]
When viewing long pages on my iPhone and iPad, the bottom of the middle column is cut off when I scroll all the way to the bottom.

![2020-03-19 10 21 48](https://user-images.githubusercontent.com/5209952/77077539-bb4ec280-69cb-11ea-9560-e3020f53ccde.png)

**Comment by gebner** [comment]
I think this is fixed by #25

**Comment by bryangingechen** [comment]
This now sometimes happens for the left and right columns on my iPhone and iPad. Possibly related to some webkit bug? I'll keep investigating. https://stackoverflow.com/questions/29531718/website-often-refuses-to-scroll-on-iphone-safari
