### ISSUE TITLE
double dashes become single dashes in display

### ISSUE THREAD

**Issue by robertylewis** [leanprover-community/doc-gen#17]
I haven't investigated this yet. Leaving it as a note for myself.

Double dashes `--` in source code become single dashes `-` in the displayed html, even when they appear in code blocks. See:

https://github.com/leanprover-community/mathlib/blob/master/src/tactic/doc_commands.lean#L255
https://leanprover-community.github.io/mathlib_docs/commands.html#library_note

where it could easily lead to misunderstandings.

**Comment by gebner** [comment]
Wow, do you know where the bug is coming from.

**Comment by jcommelin** [comment]
Also, it's not all `--`, because just below Rob's example there is `-- See Note [open expressions]`.

**Comment by bryangingechen** [comment]
There seems to be a bug somewhere in Lean:
```lean
/--
/-- nested docstring -/
-/
def foo := 1
open tactic
run_cmd do
  s ← doc_string `foo,
  trace s
-- /- nested docstring -/
```

**Comment by bryangingechen** [comment]
I might have screwed something up in https://github.com/leanprover-community/lean/pull/113/... investigating.
