### ISSUE TITLE
Linking to a definition should scroll to the definition

### ISSUE THREAD

**Issue by gebner** [leanprover-community/doc-gen#23]
I just followed a link from the 100 page: https://leanprover-community.github.io/mathlib_docs/field_theory/finite.html#nat.modeq.pow_totient

It took me a while to find the theorem.  Usually the browser would scroll to the theorem and put it at the top of the page.  But here this doesn't work because it is the last theorem.  A common workaround is to put one page of whitespace at the end.

**Comment by robertylewis** [comment]
Alternatively we could highlight the anchored decl somehow. Do you prefer the page of whitespace?

**Comment by gebner** [comment]
Highlighting would be great.  Personally I would still like some whitespace at the end so that I don't have to read at the bottom of the screen.

**Comment by robertylewis** [comment]
The whitespace change is very easy; I don't have time today to implement the JS highlighting.
