### ISSUE TITLE
Back/forward buttons ignore fragments

### ISSUE THREAD

**Issue by gebner** [leanprover-community/doc-gen#24]
1. Click on this link: https://leanprover-community.github.io/mathlib_docs/field_theory/finite.html#nat.modeq.pow_totient
 2. Alt-Left
 3. Alt-Right

At least on firefox, the page then scrolls up to the very top and you don't see `nat.modeq.pow_totient`.

**Comment by robertylewis** [comment]
Huh. I can look into this at some point but neither the cause nor the solution is immediately clear to me.
