### ISSUE TITLE
«R»

### ISSUE THREAD

**Issue by gebner** [leanprover-community/doc-gen#82]
![quoted_r](https://user-images.githubusercontent.com/313929/94579251-e4081c80-0278-11eb-85c9-8c08e623ce73.png)

https://leanprover-community.github.io/mathlib_docs/ring_theory/algebra.html#algebra_map

**Comment by bryangingechen** [comment]
[Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/quote.20mark.20in.20doc)
