### ISSUE TITLE
W

### ISSUE THREAD

**Issue by bryangingechen** [leanprover-community/doc-gen#83]
A `W` in an unrelated module doc links to [the "W" in W-type](https://leanprover-community.github.io/mathlib_docs/data/W.html#W): https://leanprover-community.github.io/mathlib_docs/representation_theory/maschke.html

Should we rename / namespace W-types or just try to avoid using it as a variable name?

**Comment by gebner** [comment]
I would vote to rename `W`.

**Comment by robertylewis** [comment]
I agree, that name makes me slightly uncomfortable. I don't like single character identifiers in root.

**Comment by digama0** [comment]
It's a bit unfortunate that this is literally the name used in the literature. Perhaps `W_type` instead?

**Comment by bryangingechen** [comment]
Is there a reasonable namespace we can put it in?

**Comment by digama0** [comment]
I don't know about that; it doesn't seem any more tied to a namespace as other basic types like `list` or `tree`. It's a really basic (fundamental in the sense of close to the axioms) type, not tied to any particular mathematics except type theory.

**Comment by gebner** [comment]
Looking through https://ncatlab.org/nlab/show/W-type, Moerdijk seems to like the name "wellfounded tree".  So maybe we could use `wellfounded_tree` or `wf_tree`.

**Comment by digama0** [comment]
I still see "W-type" being used far more often than either "W" or "wellfounded tree" in that page, including in particular the title. So I will reiterate my `W_type` suggestion.

**Comment by cipher1024** [comment]
It could be in the namespace of polynomial functors
