### ISSUE TITLE
_ = _ equations

### ISSUE THREAD

**Issue by bryangingechen** [leanprover-community/doc-gen#84]
See https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/Oddity.20in.20online.20documentation.20for.20subsingletion/near/207913178

Maybe this should be a Lean issue?

Another example:

https://leanprover-community.github.io/mathlib_docs/group_theory/order_of_element.html#subgroup.is_cyclic

**Comment by gebner** [comment]
Maybe we should just omit equations for Prop-valued definitions?

**Comment by robertylewis** [comment]
#85 

Maybe Lean should make Prop-valued instances `lemma`s instead of `def`s?

**Comment by gebner** [comment]
> Maybe Lean should make Prop-valued instances lemmas instead of defs?

I think that's a good idea, but I'll let somebody else implement it.
