### ISSUE TITLE
Some `source` links are broken (bad commit hash)

### ISSUE THREAD

**Issue by ammkrn** [leanprover-community/doc-gen#92]
Some of the links meant to take users to the source for an item are broken. The source link for `list.pmap` points to 
```
https://github.com/leanprover-community/mathlib/blob/69db7a3/src/data/list/basic.lean#L2484
```
Which I think only 404s because the commit hash is for latest commit to the mathlib repo as a whole. Swapping in the hash of the last commit that made changes to data/list/basic makes the link work, or apparently you can just point to `master`. These both seem to work fine:
```
https://github.com/leanprover-community/mathlib/blob/c141eed/src/data/list/basic.lean#L2484
https://github.com/leanprover-community/mathlib/blob/master/src/data/list/basic.lean#L2484
```

**Comment by bryangingechen** [comment]
Hmm, adding one more character from the hash for that commit works:

https://github.com/leanprover-community/mathlib/blob/69db7a33/src/data/list/basic.lean

**Comment by gebner** [comment]
Hmm, then the hash is probably ambiguous and we should use longer hashes.

**Comment by bryangingechen** [comment]
See also [the discussion on Zulip](https://leanprover.zulipchat.com/#narrow/stream/217875-Is-there.20code.20for.20X.3F/topic/Surreal.20numbers/near/214707841).

**Comment by ammkrn** [comment]
Nice detective work, I stand corrected.

I'm not a github expert, what's the downside of using the branch name instead of a commit hash?

**Comment by bryangingechen** [comment]
The docs are only built every ~2 hours so it won't always be up-to-date with the branch head.
