### ISSUE TITLE
Some code snippets start with the word `lean`

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover-community/doc-gen#93]
https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/Documentation.20formatting.20in.20tactic.2Elocalized

**Comment by fpvandoorn** [comment]
Has this been resolved in the meantime @robertylewis?

**Comment by gebner** [comment]
This is probably fixed now with #110.  Please reopen if the issue persists.
